### ISSUE TITLE
7-Send the selected cell to api

### ISSUE THREAD

**Issue by janis-rullis** [janis-rullis/lm1-symfony5-vue2-api#16]
* [x] Cleanup branches. https://github.com/Janis-Rullis-IT/dev/tree/master/git#remote
* [x] Branch: 16-cell
* [x] Outline cells with a black border. https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/16#issuecomment-711902125
* [x] Mark them with row, col value when iterating. https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/16#issuecomment-712075591
* [x] Send only the selected row-col value. https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/16#issuecomment-712091788

**Comment by janis-rullis** [comment]
# Outline cells with a black border

![image](https://user-images.githubusercontent.com/17935810/96426366-d1449000-1205-11eb-96f8-0079b66aa5a8.png)

**Comment by janis-rullis** [comment]
# Mark them with row, col value when iterating

![image](https://user-images.githubusercontent.com/17935810/96443473-54211700-1215-11eb-9e8f-f6ae28d46d28.png)

**Comment by janis-rullis** [comment]
# Send to API where it will be validated and stored

![image](https://user-images.githubusercontent.com/17935810/96444401-deb64600-1216-11eb-8e54-e7a84f7182da.png)
