### ISSUE TITLE
Handle the end of the match in the api

### ISSUE THREAD

**Issue by janis-rullis** [janis-rullis/lm1-symfony5-vue2-api#19]
After a step is made #18.
 
* [x] FInd how to calculate the win. https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/19#issuecomment-712885656

## In the `selectCell()`

* Insert the move.

## After that check if that the specific symbol has won

* [x] Collect moves by the symbol (most probably the UNIQUE INDEX must be updated). https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/19#issuecomment-712891059
* [x] ~Do the check (if possible) in the DB because it is better for data operations than PHP.  https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/19#issuecomment-712891515~ https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/35
* [x] If won, then set `game.status` = 'completed' and respond with a state.
* [x] If not, then everything works as till now.

**Comment by janis-rullis** [comment]
# TTT win logic examples

* https://jayeshkawli.ghost.io/tic-tac-toe/
* https://helloacm.com/algorithm-to-find-the-winner-on-a-tic-tac-toe-game/
* https://codereview.stackexchange.com/questions/116830/check-if-a-game-of-tic-tac-toe-has-a-winner
* https://pythonprogramming.net/horizontal-winner-learn-python-3-tutorials/
* https://leetcode.com/problems/find-winner-on-a-tic-tac-toe-game/
* https://github.com/4db/tictactoe-php/blob/master/classes/Game.php

## Steps

* Check rows.
* Check columns.
* Check diognals.

**Comment by janis-rullis** [comment]
# Collect moves by the symbol (most probably the UNIQUE INDEX must be updated)

## No need to change the index

```sql
explain SELECT `row`, `column` FROM `move` WHERE game_id = 1 and symbol = 'x'
```

![image](https://user-images.githubusercontent.com/17935810/96599800-f5cd6480-12f8-11eb-8a20-9f514dddc625.png)

**Comment by janis-rullis** [comment]
# Do the check (if possible) in the DB because it is better for data operations than PHP

* [x] Check rows.
* [x] Check columns.
* ~Check diognals.~ Later in https://github.com/janis-rullis/lm1-symfony5-vue2-api/issues/34

**Comment by janis-rullis** [comment]
# Proof
![Screenshot_2020-10-20_20-29-00](https://user-images.githubusercontent.com/17935810/96622803-17d3e080-1313-11eb-8f9c-55cd9f3c33da.png)
